version: '3.7'

services:
  notary:
    image: corda/corda-zulu-java1.8-4.4
    container_name: creditum-notary
    ports:
      - "10003:10201"
      - "2000:2222"
    volumes:
      - ${PWD}/notary/node.conf:/etc/corda/node.conf
      - ${PWD}/notary/certificates:/opt/corda/certificates
      - ${PWD}/notary/persistence:/opt/corda/persistence
      - ${PWD}/notary/logs:/opt/corda/logs
      - ${PWD}/shared/cordapps:/opt/corda/cordapps
      - ${PWD}/shared/node-infos:/opt/corda/additional-node-infos
      - ${PWD}/shared/network-parameters:/opt/corda/network-parameters

  bank:
    image: corda/corda-zulu-java1.8-4.4
    container_name: bank
    ports:
      - "10006:10201"
      - "2001:2222"
    volumes:
      - ${PWD}/bank/node.conf:/etc/corda/node.conf
      - ${PWD}/bank/certificates:/opt/corda/certificates
      - ${PWD}/bank/persistence:/opt/corda/persistence
      - ${PWD}/bank/logs:/opt/corda/logs
      - ${PWD}/shared/cordapps:/opt/corda/cordapps
      - ${PWD}/shared/node-infos:/opt/corda/additional-node-infos
      - ${PWD}/shared/network-parameters:/opt/corda/network-parameters

  corporation:
    image: corda/corda-zulu-java1.8-4.4
    container_name: corporation
    ports:
      - "10009:10201"
      - "2002:2222"
    volumes:
      - ${PWD}/corporation/node.conf:/etc/corda/node.conf
      - ${PWD}/corporation/certificates:/opt/corda/certificates
      - ${PWD}/corporation/persistence:/opt/corda/persistence
      - ${PWD}/corporation/logs:/opt/corda/logs
      - ${PWD}/shared/cordapps:/opt/corda/cordapps
      - ${PWD}/shared/node-infos:/opt/corda/additional-node-infos
      - ${PWD}/shared/network-parameters:/opt/corda/network-parameters

  hedge-fund:
    image: corda/corda-zulu-java1.8-4.4
    container_name: hedge-fund
    ports:
      - "10012:10201"
      - "2003:2222"
    volumes:
      - ${PWD}/hedge-fund/node.conf:/etc/corda/node.conf
      - ${PWD}/hedge-fund/certificates:/opt/corda/certificates
      - ${PWD}/hedge-fund/persistence:/opt/corda/persistence
      - ${PWD}/hedge-fund/logs:/opt/corda/logs
      - ${PWD}/shared/cordapps:/opt/corda/cordapps
      - ${PWD}/shared/node-infos:/opt/corda/additional-node-infos
      - ${PWD}/shared/network-parameters:/opt/corda/network-parameters
